/** Service families used for nav mega-menu and hub grouping. */
export type ServiceGroupId = "bathroom-glass" | "mirrors-glass" | "windows-doors" | "glass-services";

export interface ServiceGroup {
  id: ServiceGroupId;
  name: string;
  /** Short line describing what the family covers, used in the mega menu. */
  summary: string;
}

/**
 * One imported job photograph. Generated by scripts/import-service-media.ps1.
 * `service` is the source folder it was filed under, which is a grouping hint,
 * not a verified description of the frame.
 */
export interface ServiceMedia {
  src: string;
  group: string;
  service: string;
  width: number;
  height: number;
}

export interface Photo {
  src: string;
  alt: string;
  width: number;
  height: number;
  /**
   * Licensed stock, not a Martinez Orlyn Glass & Mirror job photograph. Anything that
   * captions a photo as this company's own work must skip a flagged frame.
   */
  stock?: boolean;
}

export interface FAQ {
  question: string;
  /** Answer opens with a direct 1-2 sentence response, then context (AEO). */
  answer: string;
}

export interface ProcessStep {
  title: string;
  body: string;
}

export interface Benefit {
  title: string;
  body: string;
}

/** A prose block on a service page. Rendered as an h2 + paragraphs (+ list). */
export interface ContentBlock {
  heading: string;
  paragraphs: string[];
  bullets?: string[];
}

/**
 * Visual treatment for a service page hero. Distinct services get distinct
 * layouts so pages do not read as one template repeated fourteen times.
 */
export type ServiceHeroVariant = "image-right" | "image-full" | "urgent" | "typographic";

export interface Service {
  slug: string;
  /** Short label used in navigation and cards. */
  name: string;
  /** Matches the folder the job photographs are filed under. */
  group: ServiceGroupId;
  seoTitle: string;
  metaDescription: string;
  h1: string;
  eyebrow: string;
  /** One-line description used on cards and in the footer. */
  cardSummary: string;
  /** Opening paragraph on the service page, below the h1. */
  intro: string;
  /**
   * Direct answer block (AEO). One question a searcher actually types, answered
   * in the first two sentences so an answer engine or a featured snippet can
   * lift it whole, followed by the facts that qualify it. Rendered on the page
   * and emitted into the FAQPage schema, so the visible text and the structured
   * data are the same words.
   */
  aeo: {
    question: string;
    answer: string;
    facts: { label: string; value: string }[];
  };
  heroVariant: ServiceHeroVariant;
  heroImage: Photo | null;
  /** When the customer typically needs this service. */
  signals: { heading: string; items: string[] };
  benefits: Benefit[];
  process: ProcessStep[];
  content: ContentBlock[];
  gallery: Photo[];
  faq: FAQ[];
  /** Slugs of contextually related services, for internal linking. */
  related: string[];
  /** Priority services double as Google Ads landing pages. */
  adsLanding: boolean;
}

export interface ServiceArea {
  slug: string;
  city: string;
  state: string;
  stateCode: string;
  county: string;
  /** Approximate road distance from Houston, TX, in miles. 0 for Houston. */
  distanceMiles: number;
  seoTitle: string;
  metaDescription: string;
  h1: string;
  eyebrow: string;
  /** Unique opening copy. Never a templated string with the city swapped in. */
  intro: string;
  /** Two to three paragraphs of area-specific context. */
  context: ContentBlock;
  /** Service slugs that matter most in this area, with a local reason. */
  featuredServices: { slug: string; note: string }[];
  /** Slugs of neighbouring service areas. */
  nearbyAreas: string[];
  faq: FAQ[];
}

export interface NavItem {
  label: string;
  href: string;
  children?: NavItem[];
}

export interface GalleryItem extends Photo {
  category: string;
  caption: string;
}

export interface BeforeAfterItem {
  id: string;
  title: string;
  caption: string;
  category: string;
  before: Photo;
  after: Photo;
}

/**
 * A published customer review. The site ships with none: the component reads
 * this array and hides itself when empty rather than showing invented praise.
 */
export interface Testimonial {
  quote: string;
  author: string;
  location: string;
  source: string;
}

export interface EstimateSubmission {
  fullName: string;
  phone: string;
  email?: string;
  service: string;
  cityOrZip: string;
  propertyType: string;
  details: string;
  pageUrl?: string;
  attribution?: Record<string, string>;
}
